### PR TITLE
add first integration tests

### LINKED ISSUE #13: Output Github-style problem messages when running in an action
::warning

### LINKED ISSUE #15: Docummentation: Add a readme
Add a README that includes docs on:

- [x] What the project is
- [ ] Installing the project
- [x] Using the project
- [x] Info on Github action output
- [ ] Link to in depth docs
- [x] Licence

also add readme linting to this project

### PR DESCRIPTION
**Pull request by chee**
what do we think of this?

if it seems good, i'll add more. it relates to #31
also relates to #14 and includes code that closes #13

it also adds a readme, which closes #15 
more in-depth documentation is tracked in a separate issue: https://github.com/Financial-Times/origami-component-manifest-linter/issues/16

### CODE REVIEW

**Comment by notlee** [comment]
The overall approach looks pretty good to me! Two pieces of feedback: 
- It took me a little while to understand how the tests work, adding some codedocs and a readme as you add more tests would be much appreciated :) 
- I'm wondering about using `getProblemsAndOpinions` in the test runner though, maybe not a good idea to use the code under test to make assertions about its output?

**Review by JakeChampion — APPROVED** [review]

**Comment by chee** [comment]
> The overall approach looks pretty good to me! Two pieces of feedback:
> 
> * It took me a little while to understand how the tests work, adding some codedocs and a readme as you add more tests would be much appreciated :)

i will add some comments

> * I'm wondering about using `getProblemsAndOpinions` in the test runner though, maybe not a good idea to use the code under test to make assertions about its output?

the `getProblemsAndOpinions` isn't really under test here. though we do check that it isn't returning anything other than problems and opinions. 

i don't think it would be better to write a new untested function than to use a function that's already written. i'll add specific unit tests to ensure `getProblemsAndOpinions` is valid too.

**Comment by chee** [comment]
>  and a readme as you add more tests 

oh, and i'll add a readme.md to the `integration-tests` folder too :)

**Comment by chee** [comment]
i'll try a new approach

**Comment by chee** [comment]
okay, so i'm going to write a new printer to generate the output expected by github actions
and then parse that in the tests

that'll close #13 at the same time and won't use the `getProblemsAndOpinions` generator

**Review by origamiserviceuser — APPROVED** [review]
This is really nice Chee ☺️

**Comment by chee** [comment]
here's the readme for the integration tests: https://github.com/Financial-Times/origami-component-manifest-linter/blob/0a6009c8ff639de3573993a74c7309b2c05db7fe/integration-tests/readme.md

**Comment by chee** [comment]
i'll merge this in, because it looks like a good start

**Comment by notlee** [comment]
🙌

**Pull request merged**
